# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Darren Royle ~ Curriculum Vitae
email: royletron@gmail.com
description: > # Curriculum Vitae of Darren Royle. Software developer and manager with a decade of experience in delivering applications in many different languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cv.royletron.dev" # the base hostname & protocol for your site
twitter_username: royletron
github_username:  royletron

# Build settings
markdown: kramdown
