# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Adam ~ Curriculum Vitae
email: james.a.adam.94@gmail.com
description: > # Curriculum Vitae of James Adam. Software developer and aspiring builder of cool things.
baseurl: "/cv" # the subpath of your site, e.g. /blog
url: "http://jamesadam.dev" # the base hostname & protocol for your site
github_username:  James-Adam

# Build settings
markdown: kramdown
